require('plugins')
require('keybindings')
require('options')
require('treesitter-config')
require('autopairs-config')
require('lualine-config')
require('bufferline-config')
--require('nvim-tree-config')
require('nerd-tree-config')
require('whichkey-config')
require('telescope-config')
require('cmp-config')
require('tabnine-config')
require('tokyo-config')
require('autosave-config')
--vim.cmd('colorscheme tokyonight')
vim.cmd('colorscheme NeoSolarized')
